
export const GET_SINGLE_USER_DETAILS_REQUEST = 'GET_SINGLE_USER_DETAILS_REQUEST';
export const GET_SINGLE_USER_DETAILS_SUCCESS = 'GET_SINGLE_USER_DETAILS_SUCCESS';
export const GET_SINGLE_USER_DETAILS_ERROR = 'GET_SINGLE_USER_DETAILS_ERROR';

export const GET_ALL_USER_DETAILS_REQUEST = 'GET_ALL_USER_DETAILS_REQUEST';
export const GET_ALL_USER_DETAILS_SUCCESS = 'GET_ALL_USER_DETAILS_SUCCESS';
export const GET_ALL_USER_DETAILS_ERROR = 'GET_ALL_USER_DETAILS_ERROR';






